/**
 * Framework reference catalogue. Keyed by the framework code used in
 * `FRAMEWORKS` (packages/shared/src/constants.ts). `parent` refers to another
 * refCode within the same framework and produces the tree.
 */
export interface FrameworkRefSeed {
  refCode: string;
  title: string;
  description?: string;
  parent?: string;
}

export const FRAMEWORK_DESCRIPTIONS: Record<string, string> = {
  COSO: 'Committee of Sponsoring Organizations Internal Control - Integrated Framework (2013): five components and seventeen principles.',
  COBIT: 'ISACA COBIT 2019 governance and management objectives for enterprise IT.',
  ISO31000: 'ISO 31000:2018 risk management principles, framework and process.',
  ISO27001: 'ISO/IEC 27001:2022 information security management system requirements and Annex A controls.',
  IFRS: 'IFRS Accounting Standards most relevant to financial reporting risk in the region.',
  SOX: 'Sarbanes-Oxley Act of 2002 sections used for internal control over financial reporting.',
  IIA: 'IIA Global Internal Audit Standards (effective January 2025), domains I to V.',
};

export const FRAMEWORK_REFERENCES: Record<string, FrameworkRefSeed[]> = {
  COSO: [
    { refCode: 'CE', title: 'Control Environment' },
    { refCode: 'CE-1', title: 'Demonstrates commitment to integrity and ethical values', parent: 'CE' },
    { refCode: 'CE-2', title: 'Exercises oversight responsibility', parent: 'CE' },
    { refCode: 'CE-3', title: 'Establishes structure, authority and responsibility', parent: 'CE' },
    { refCode: 'CE-4', title: 'Demonstrates commitment to competence', parent: 'CE' },
    { refCode: 'CE-5', title: 'Enforces accountability', parent: 'CE' },
    { refCode: 'RA', title: 'Risk Assessment' },
    { refCode: 'RA-6', title: 'Specifies suitable objectives', parent: 'RA' },
    { refCode: 'RA-7', title: 'Identifies and analyses risk', parent: 'RA' },
    { refCode: 'RA-8', title: 'Assesses fraud risk', parent: 'RA' },
    { refCode: 'RA-9', title: 'Identifies and analyses significant change', parent: 'RA' },
    { refCode: 'CA', title: 'Control Activities' },
    { refCode: 'CA-10', title: 'Selects and develops control activities', parent: 'CA' },
    { refCode: 'CA-11', title: 'Selects and develops general controls over technology', parent: 'CA' },
    { refCode: 'CA-12', title: 'Deploys through policies and procedures', parent: 'CA' },
    { refCode: 'IC', title: 'Information and Communication' },
    { refCode: 'IC-13', title: 'Uses relevant information', parent: 'IC' },
    { refCode: 'IC-14', title: 'Communicates internally', parent: 'IC' },
    { refCode: 'IC-15', title: 'Communicates externally', parent: 'IC' },
    { refCode: 'MA', title: 'Monitoring Activities' },
    { refCode: 'MA-16', title: 'Conducts ongoing and/or separate evaluations', parent: 'MA' },
    { refCode: 'MA-17', title: 'Evaluates and communicates deficiencies', parent: 'MA' },
  ],
  COBIT: [
    { refCode: 'EDM', title: 'Evaluate, Direct and Monitor' },
    { refCode: 'EDM03', title: 'Ensured risk optimisation', parent: 'EDM' },
    { refCode: 'APO', title: 'Align, Plan and Organise' },
    { refCode: 'APO12', title: 'Managed risk', parent: 'APO' },
    { refCode: 'APO13', title: 'Managed security', parent: 'APO' },
    { refCode: 'BAI', title: 'Build, Acquire and Implement' },
    { refCode: 'BAI06', title: 'Managed IT changes', parent: 'BAI' },
    { refCode: 'BAI10', title: 'Managed configuration', parent: 'BAI' },
    { refCode: 'DSS', title: 'Deliver, Service and Support' },
    { refCode: 'DSS05', title: 'Managed security services', parent: 'DSS' },
    { refCode: 'DSS06', title: 'Managed business process controls', parent: 'DSS' },
    { refCode: 'MEA', title: 'Monitor, Evaluate and Assess' },
    { refCode: 'MEA02', title: 'Managed system of internal control', parent: 'MEA' },
  ],
  ISO31000: [
    { refCode: '4', title: 'Principles' },
    { refCode: '5', title: 'Framework' },
    { refCode: '5.2', title: 'Leadership and commitment', parent: '5' },
    { refCode: '5.4', title: 'Design', parent: '5' },
    { refCode: '6', title: 'Process' },
    { refCode: '6.3', title: 'Scope, context and criteria', parent: '6' },
    { refCode: '6.4', title: 'Risk assessment', parent: '6' },
    { refCode: '6.4.2', title: 'Risk identification', parent: '6.4' },
    { refCode: '6.4.3', title: 'Risk analysis', parent: '6.4' },
    { refCode: '6.4.4', title: 'Risk evaluation', parent: '6.4' },
    { refCode: '6.5', title: 'Risk treatment', parent: '6' },
    { refCode: '6.6', title: 'Monitoring and review', parent: '6' },
  ],
  ISO27001: [
    { refCode: 'A.5', title: 'Organisational controls' },
    { refCode: 'A.5.15', title: 'Access control', parent: 'A.5' },
    { refCode: 'A.5.16', title: 'Identity management', parent: 'A.5' },
    { refCode: 'A.5.18', title: 'Access rights', parent: 'A.5' },
    { refCode: 'A.5.19', title: 'Information security in supplier relationships', parent: 'A.5' },
    { refCode: 'A.6', title: 'People controls' },
    { refCode: 'A.6.1', title: 'Screening', parent: 'A.6' },
    { refCode: 'A.7', title: 'Physical controls' },
    { refCode: 'A.8', title: 'Technological controls' },
    { refCode: 'A.8.2', title: 'Privileged access rights', parent: 'A.8' },
    { refCode: 'A.8.5', title: 'Secure authentication', parent: 'A.8' },
    { refCode: 'A.8.32', title: 'Change management', parent: 'A.8' },
  ],
  IFRS: [
    { refCode: 'IAS 1', title: 'Presentation of Financial Statements' },
    { refCode: 'IAS 7', title: 'Statement of Cash Flows' },
    { refCode: 'IAS 12', title: 'Income Taxes' },
    { refCode: 'IAS 16', title: 'Property, Plant and Equipment' },
    { refCode: 'IAS 19', title: 'Employee Benefits' },
    { refCode: 'IAS 37', title: 'Provisions, Contingent Liabilities and Contingent Assets' },
    { refCode: 'IFRS 9', title: 'Financial Instruments' },
    { refCode: 'IFRS 15', title: 'Revenue from Contracts with Customers' },
    { refCode: 'IFRS 16', title: 'Leases' },
    { refCode: 'IFRS 17', title: 'Insurance Contracts' },
  ],
  SOX: [
    { refCode: '302', title: 'Corporate responsibility for financial reports' },
    { refCode: '302(a)(4)', title: 'Officers responsible for internal controls', parent: '302' },
    { refCode: '404', title: 'Management assessment of internal controls' },
    { refCode: '404(a)', title: 'Management report on internal control over financial reporting', parent: '404' },
    { refCode: '404(b)', title: 'Auditor attestation', parent: '404' },
    { refCode: '409', title: 'Real-time issuer disclosures' },
    { refCode: '802', title: 'Criminal penalties for altering documents' },
    { refCode: '906', title: 'Corporate responsibility for financial reports (criminal)' },
  ],
  IIA: [
    { refCode: 'I', title: 'Domain I: Purpose of Internal Auditing' },
    { refCode: 'II', title: 'Domain II: Ethics and Professionalism' },
    { refCode: '2.1', title: 'Individual objectivity', parent: 'II' },
    { refCode: '3.1', title: 'Competency', parent: 'II' },
    { refCode: '4.2', title: 'Due professional care', parent: 'II' },
    { refCode: 'III', title: 'Domain III: Governing the Internal Audit Function' },
    { refCode: '6.1', title: 'Internal audit mandate', parent: 'III' },
    { refCode: 'IV', title: 'Domain IV: Managing the Internal Audit Function' },
    { refCode: '9.4', title: 'Internal audit plan', parent: 'IV' },
    { refCode: '12.3', title: 'Oversee and improve engagement performance', parent: 'IV' },
    { refCode: 'V', title: 'Domain V: Performing Internal Audit Services' },
    { refCode: '13.3', title: 'Engagement objectives and scope', parent: 'V' },
    { refCode: '13.6', title: 'Work programme', parent: 'V' },
    { refCode: '14.3', title: 'Evaluation of findings', parent: 'V' },
    { refCode: '14.6', title: 'Engagement documentation', parent: 'V' },
    { refCode: '15.1', title: 'Final engagement communication', parent: 'V' },
    { refCode: '15.2', title: 'Confirming the implementation of recommendations or action plans', parent: 'V' },
  ],
};
